
#include "res://addons/lygia_godot/sample/2DCube.glsl"
#include "res://addons/lygia_godot/sample/derivative.glsl"
#include "res://addons/lygia_godot/sample/heatmap.glsl"
#include "res://addons/lygia_godot/sample/quilt.glsl"#include "res://addons/lygia_godot/sample/sprite.glsl"
#include "res://addons/lygia_godot/sample/3DSdf.glsl"#include "res://addons/lygia_godot/sample/dither.glsl"
#include "res://addons/lygia_godot/sample/hue.glsl"#include "res://addons/lygia_godot/sample/repeat.glsl"
#include "res://addons/lygia_godot/sample/triplanar.glsl"
#include "res://addons/lygia_godot/sample/bicubic.glsl"#include "res://addons/lygia_godot/sample/dof.glsl"#include "res://addons/lygia_godot/sample/mirror.glsl"#include "res://addons/lygia_godot/sample/shadow.glsl"
#include "res://addons/lygia_godot/sample/untile.glsl"
#include "res://addons/lygia_godot/sample/bracketing.glsl"
#include "res://addons/lygia_godot/sample/equirect.glsl"#include "res://addons/lygia_godot/sample/nearest.glsl"
#include "res://addons/lygia_godot/sample/shadowLerp.glsl"
#include "res://addons/lygia_godot/sample/viewPosition.glsl"
#include "res://addons/lygia_godot/sample/bumpMap.glsl"#include "res://addons/lygia_godot/sample/flow.glsl"
#include "res://addons/lygia_godot/sample/normalMap.glsl"#include "res://addons/lygia_godot/sample/shadowPCF.glsl"#include "res://addons/lygia_godot/sample/yuv.glsl"
#include "res://addons/lygia_godot/sample/clamp2edge.glsl"
#include "res://addons/lygia_godot/sample/fxaa.glsl"#include "res://addons/lygia_godot/sample/opticalFlow.glsl"
#include "res://addons/lygia_godot/sample/smooth.glsl"
#include "res://addons/lygia_godot/sample/zero.glsl"
#include "res://addons/lygia_godot/sample/normalFromHeightMap.glsl"
