
#include "res://sample/2DCube.glsl"
#include "res://sample/derivative.glsl"
#include "res://sample/heatmap.glsl"
#include "res://sample/quilt.glsl"#include "res://sample/sprite.glsl"
#include "res://sample/3DSdf.glsl"#include "res://sample/dither.glsl"
#include "res://sample/hue.glsl"#include "res://sample/repeat.glsl"
#include "res://sample/triplanar.glsl"
#include "res://sample/bicubic.glsl"#include "res://sample/dof.glsl"#include "res://sample/mirror.glsl"#include "res://sample/shadow.glsl"
#include "res://sample/untile.glsl"
#include "res://sample/bracketing.glsl"
#include "res://sample/equirect.glsl"#include "res://sample/nearest.glsl"
#include "res://sample/shadowLerp.glsl"
#include "res://sample/viewPosition.glsl"
#include "res://sample/bumpMap.glsl"#include "res://sample/flow.glsl"
#include "res://sample/normalMap.glsl"#include "res://sample/shadowPCF.glsl"#include "res://sample/yuv.glsl"
#include "res://sample/clamp2edge.glsl"
#include "res://sample/fxaa.glsl"#include "res://sample/opticalFlow.glsl"
#include "res://sample/smooth.glsl"
#include "res://sample/zero.glsl"
#include "res://sample/normalFromHeightMap.glsl"
